// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Objetivos.Web.Data;

#nullable disable

namespace Objetivos.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CambiosJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EntidadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Autoevaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivosAdjuntosJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenciasMencionadasJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaAutoevaluacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoftSkill1Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftSkill1Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoftSkill2Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SoftSkill2Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoId")
                        .IsUnique();

                    b.ToTable("Autoevaluaciones");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.BitacoraEntrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdjuntosJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaFeedback")
                        .HasColumnType("TEXT");

                    b.Property<string>("FeedbackJefe")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("BitacoraEntradas");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsSuperusuario")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<int>("JefeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("JefeId");

                    b.HasIndex("PaisId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.EvaluacionFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComentarioJefe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EvaluadorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PuntajeFinal")
                        .HasColumnType("REAL");

                    b.Property<int>("ResultadoFinal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoId")
                        .IsUnique();

                    b.ToTable("EvaluacionesFinales");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.EventoCalendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("EventosCalendario");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Jefe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AreaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DebeCambiarPassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsSuperusuario")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PaisId");

                    b.ToTable("Jefes");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.MensajeChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DestinatarioEmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("JefeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Leido")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RemitenteEsJefe")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RemitenteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MensajesChat");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Leida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Objetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PilarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progreso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftSkill1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoftSkill2Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("SoftSkill1Id");

                    b.HasIndex("SoftSkill2Id");

                    b.HasIndex("PilarId", "EmpleadoId", "Anio")
                        .IsUnique();

                    b.ToTable("Objetivos");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Pilar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pilares");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.RevisionCuatrimestral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComentarioJefe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completada")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EvaluadorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenciasRevisadasJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaEvaluacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("ObjetivoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Periodo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Puntaje")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Resultado")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("RevisionesCuatrimestrales");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.SoftSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SoftSkills");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Autoevaluacion", b =>
                {
                    b.HasOne("Objetivos.Web.Domain.Entities.Objetivo", "Objetivo")
                        .WithOne("Autoevaluacion")
                        .HasForeignKey("Objetivos.Web.Domain.Entities.Autoevaluacion", "ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objetivo");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.BitacoraEntrada", b =>
                {
                    b.HasOne("Objetivos.Web.Domain.Entities.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Objetivos.Web.Domain.Entities.Objetivo", "Objetivo")
                        .WithMany("Bitacora")
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Objetivo");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("Objetivos.Web.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Objetivos.Web.Domain.Entities.Jefe", "Jefe")
                        .WithMany()
                        .HasForeignKey("JefeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Objetivos.Web.Domain.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Jefe");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.EvaluacionFinal", b =>
                {
                    b.HasOne("Objetivos.Web.Domain.Entities.Objetivo", "Objetivo")
                        .WithOne("EvaluacionFinal")
                        .HasForeignKey("Objetivos.Web.Domain.Entities.EvaluacionFinal", "ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objetivo");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.EventoCalendario", b =>
                {
                    b.HasOne("Objetivos.Web.Domain.Entities.Objetivo", "Objetivo")
                        .WithMany()
                        .HasForeignKey("ObjetivoId");

                    b.Navigation("Objetivo");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Jefe", b =>
                {
                    b.HasOne("Objetivos.Web.Domain.Entities.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Objetivos.Web.Domain.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Objetivo", b =>
                {
                    b.HasOne("Objetivos.Web.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Objetivos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Objetivos.Web.Domain.Entities.Pilar", "Pilar")
                        .WithMany()
                        .HasForeignKey("PilarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Objetivos.Web.Domain.Entities.SoftSkill", "SoftSkill1")
                        .WithMany()
                        .HasForeignKey("SoftSkill1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Objetivos.Web.Domain.Entities.SoftSkill", "SoftSkill2")
                        .WithMany()
                        .HasForeignKey("SoftSkill2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Pilar");

                    b.Navigation("SoftSkill1");

                    b.Navigation("SoftSkill2");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.RevisionCuatrimestral", b =>
                {
                    b.HasOne("Objetivos.Web.Domain.Entities.Objetivo", "Objetivo")
                        .WithMany("Revisiones")
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objetivo");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Objetivos");
                });

            modelBuilder.Entity("Objetivos.Web.Domain.Entities.Objetivo", b =>
                {
                    b.Navigation("Autoevaluacion");

                    b.Navigation("Bitacora");

                    b.Navigation("EvaluacionFinal");

                    b.Navigation("Revisiones");
                });
#pragma warning restore 612, 618
        }
    }
}
